services:
  - type: web
    name: my-fastapi-app
    env: python
    plan: free
    buildCommand: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      source venv/bin/activate
      uvicorn main:app --host 0.0.0.0 --port 8080
    envVars:
      - key: PORT
        value: 8080
